spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/e-gou
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    template-loader-path: /WEB-INF/
    suffix: .ftl
  resources:
    static-locations: /META-INF/resources/,classpath:/resources/
mybatis: 
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.ddu.entity
server:
  address: 127.0.0.1
  port: 8080
  context-path: /
  session:
    timeout: 30
logging:
  file: C:/log.log